// Residential styles keep their designed plot sizes; shops occupy one cell.
export const LEGACY_WIDE_PRIVATE_KINDS = new Set(['courtyard','spanish','french','italian','teaHouse','market','diner','mediterranean','office','hotel']);
export const BUSINESS_KINDS = {
  parisApartment:{zone:'residential',footprint:2,cost:1600,name:'巴黎奥斯曼公寓',architecture:'parisApartment',description:'浅石街墙、连续铁艺阳台、蓝灰折线屋顶与内院；适合整片巴黎街区'},
  seineTownhouse:{zone:'residential',footprint:1,cost:280,name:'塞纳河岸联排',architecture:'seineTownhouse',description:'奶油色窄立面、细长窗、石檐与阁楼老虎窗；适合滨河旧城街巷'},
  londonTerrace:{zone:'residential',footprint:2,cost:1280,name:'伦敦乔治式排屋',architecture:'londonTerrace',description:'连贯砖色与白窗框、整齐檐口、烟囱与门前铁栏；适合连续英伦街道'},
  thamesWarehouse:{zone:'residential',footprint:2,cost:1520,name:'泰晤士河仓库公寓',architecture:'thamesWarehouse',description:'暖褐砖墙、重复山墙、大窗与保留的吊装梁；滨河仓库改造住宅'},
  courtyard: {zone:'residential', footprint:2, cost:960, name:'四合院住宅', chinese:true, description:'灰瓦院落、朱红院门与围合天井'},
  lingnan: {zone:'residential', footprint:1, cost:140, name:'岭南民居', chinese:true, description:'浅墙青瓦、骑楼廊柱与通风阳台'},
  spanish: {zone:'residential', footprint:2, cost:720, name:'西班牙庭院住宅', architecture:'spanish', description:'暖白灰泥、L 形陶瓦屋顶、拱形门廊与花池'},
  french: {zone:'residential', footprint:2, cost:1800, name:'法国花园公馆', architecture:'french', description:'浅石立面、蓝灰折线屋顶、老虎窗与铁艺阳台'},
  japanese: {zone:'residential', footprint:1, cost:180, name:'日本和风住宅', architecture:'japanese', description:'灰瓦深檐、细木格栅、缘侧木廊与袖珍枯山水；升级精修庭院和木作，保留低层和宅轮廓'},
  kyotoMachiya: {zone:'residential', footprint:1, cost:280, name:'京都町屋联排', architecture:'kyotoMachiya', description:'连续灰瓦街檐、出格子窗、低矮二层与暖色门灯；适合成排建设的传统日式街巷'},
  sukiyaHouse: {zone:'residential', footprint:2, cost:1360, name:'数寄屋庭院住宅', architecture:'sukiyaHouse', description:'错落低檐、通透木廊、砂庭、手水钵与庭树；围绕开放庭院逐级精修'},
  gasshoHouse: {zone:'residential', footprint:2, cost:1120, name:'合掌造乡居', architecture:'gasshoHouse', description:'陡坡茅草屋顶、木构山墙、阁楼小窗与乡居花园；升级保留合掌屋顶轮廓'},
  japaneseApartment: {zone:'residential', footprint:2, cost:1480, name:'日式阳台公寓', architecture:'japaneseApartment', description:'米白楼体、连续阳台、木色隔屏与屋顶花园；随等级长成更完整的现代日式住区'},
  nordic: {zone:'residential', footprint:1, cost:120, name:'北欧木屋', architecture:'nordic', description:'莓红木板墙、白色窗框、陡坡交叉屋顶与木平台'},
  british: {zone:'residential', footprint:1, cost:160, name:'英伦砖宅', architecture:'british', description:'红褐砖墙、双前山墙、凸窗、双烟囱与低矮花篱'},
  italian: {zone:'residential', footprint:2, cost:800, name:'意式花园住宅', architecture:'italian', description:'赭黄墙面、绿百叶窗、低坡陶瓦顶、观景亭与藤架庭院'},
  huizhou: {zone:'residential',footprint:2,cost:1040,name:'徽派马头墙院落',architecture:'huizhou',chinese:true,description:'粉墙黛瓦、层叠马头墙、木格门窗与石板小院'},
  bai: {zone:'residential',footprint:2,cost:1120,name:'白族照壁民居',architecture:'bai',chinese:true,description:'白墙蓝绘、翘檐门楼、独立照壁与花木庭院'},
  miaoVillage: {zone:'residential',footprint:2,cost:1320,name:'千户苗寨',architecture:'miaoVillage',chinese:true,description:'依坡错落的木构吊脚楼、层叠青瓦、连廊与寨中石阶'},
  tulou: {zone:'residential',footprint:2,cost:1560,name:'漳州土楼',architecture:'tulou',chinese:true,description:'夯土围合环楼、深檐灰瓦、内廊庭院与门楼'},
  jiangnan: {zone:'residential',footprint:2,cost:1200,name:'江南水乡宅院',architecture:'jiangnan',chinese:true,description:'粉墙黛瓦、临水廊台、错落院门与窄巷石桥'},
  tibetan: {zone:'residential',footprint:1,cost:340,name:'藏式碉房',architecture:'tibetan',chinese:true,description:'白石厚墙、赭红檐带、层叠平顶与经幡望台'},
  shanxiCourtyard: {zone:'residential',footprint:2,cost:1480,name:'晋商大院',architecture:'shanxiCourtyard',chinese:true,description:'青砖高墙、三进院落、垂花门楼与连排厢房'},
  hakkaWeilong: {zone:'residential',footprint:2,cost:1720,name:'客家围龙屋',architecture:'hakkaWeilong',chinese:true,description:'半月围屋、中央祖堂、横屋院坪与围合回廊'},
  dutch: {zone:'residential',footprint:1,cost:240,name:'荷兰运河屋',architecture:'dutch',description:'赭红窄立面、阶梯山墙、吊装梁与门前花箱'},
  chalet: {zone:'residential',footprint:1,cost:280,name:'阿尔卑斯木屋',architecture:'chalet',description:'石砌基座、深色木墙、宽檐双坡顶与花篮阳台'},
  teaHouse: {zone:'commercial', footprint:2, cost:1000, name:'中式茶楼', architecture:'teaHouse', chinese:true, description:'2×2 黛瓦重檐、木格茶室、雕花阳台与临街茶座；红灯笼暖窗，升级保留楼阁轮廓'},
  oldStreet: {zone:'commercial', footprint:1, cost:180, name:'便利小店', chinese:true, description:'连排铺面、木质招牌与骑楼雨廊'},
  market: {zone:'commercial', footprint:2, cost:800, name:'生鲜市场', description:'2×2 开放集市、连排摊位、彩色雨棚与装卸庭院'},
  cafe: {zone:'commercial', footprint:1, cost:220, name:'餐饮街店', description:'暖色店面、遮阳棚与露天座席'},
  tavern: {zone:'commercial', footprint:1, cost:300, name:'街角小酒馆', architecture:'tavern', description:'暖砖墙、墨绿门面、酒杯招牌与木桶露台'},
  izakaya: {zone:'commercial', footprint:1, cost:260, name:'日式居酒屋', architecture:'izakaya', description:'木质门面、红灯笼、暖帘与门前长凳'},
  kissaten: {zone:'commercial', footprint:1, cost:320, name:'日式喫茶店', architecture:'kissaten', description:'深木门面、格栅暖窗、布帘、咖啡招牌与窄檐露台'},
  bakery: {zone:'commercial', footprint:1, cost:200, name:'街角烘焙店', architecture:'bakery', description:'奶油色墙面、条纹遮阳棚、面包橱窗与露天茶座'},
  flowerShop: {zone:'commercial', footprint:1, cost:260, name:'街角花店', architecture:'flowerShop', description:'鼠尾草绿店面、玻璃花房雨棚、花桶与层叠盆栽'},
  bookstore: {zone:'commercial', footprint:1, cost:340, name:'老城书店', architecture:'bookstore', description:'暖砖立面、深绿书窗、木质书架与悬挂书页招牌'},
  foodHall: {zone:'commercial', footprint:2, cost:1800, name:'城市美食广场', architecture:'foodHall', description:'2×2 暖砖美食大厅、连续摊档、玻璃天窗、彩色雨棚与共享露台'},
  europeanArcade: {zone:'commercial', footprint:2, cost:2600, name:'欧式拱廊商场', architecture:'europeanArcade', description:'2×2 浅石拱廊、挑高橱窗、玻璃穹顶、角楼与金色商场招牌'},
  japaneseMarket: {zone:'commercial', footprint:2, cost:2200, name:'日式町家商馆', architecture:'japaneseMarket', description:'2×2 连栋町家商铺、灰瓦深檐、中央小巷、木格橱窗与暖帘灯笼'},
  diner: {zone:'commercial', footprint:1, cost:1200, name:'美式复古餐吧', architecture:'diner', description:'薄荷绿门面、银色檐口、红色卡座与高杆招牌'},
  mediterranean: {zone:'commercial', footprint:1, cost:1400, name:'地中海咖啡馆', architecture:'mediterranean', description:'白墙蓝窗、屋顶露台、蓝白遮阳棚与陶盆绿植'},
  artDeco: {zone:'commercial', footprint:1, cost:360, name:'装饰艺术精品店', architecture:'artDeco', description:'阶梯冠顶、墨绿石墙、金色竖线与几何门廊'},
  pharmacy: {zone:'commercial', footprint:1, cost:280, name:'社区药店', architecture:'pharmacy', service:'clinic', serviceRadius:4, serviceRadiusGrowth:1, serviceLabel:'基础医疗与药事服务', description:'白绿店面、醒目药房十字灯牌、药品橱窗与便民柜台，并为附近居民提供基础医疗覆盖'},
  repairGarage: {zone:'commercial', footprint:1, cost:420, name:'汽车修理店', architecture:'repairGarage', description:'宽卷帘维修工位、工具墙、轮胎架与醒目的扳手招牌'},
  laundry: {zone:'commercial', footprint:1, cost:240, name:'社区洗衣店', architecture:'laundry', description:'蓝白店面、圆形洗衣机窗、衣物护理台与晾衣标识'},
  hardware: {zone:'commercial', footprint:1, cost:320, name:'五金工具店', architecture:'hardware', description:'橙灰门面、工具陈列墙、零件货架与锤子招牌'},
  office: {zone:'commercial', footprint:2, cost:1800, name:'商务办公', description:'2×2 蓝灰玻璃办公楼、挑高门厅、入口广场与香槟金雨棚'},
  hotel: {zone:'commercial', footprint:2, cost:3600, name:'城市酒店', description:'2×2 石材客房塔楼、玻璃迎宾大堂、落客雨棚、景观庭院与屋顶花园'},
  departmentStore: {zone:'commercial', footprint:2, cost:2400, name:'城市百货商场', architecture:'departmentStore', description:'2×2 石材百货、连续展示橱窗、中央钟牌、入口雨棚与屋顶花园'},
  workshop: {zone:'industrial', name:'制造工坊', description:'锯齿厂房、排气烟囱与生产车间'},
  logistics: {zone:'industrial', footprint:2, cost:960, name:'物流仓储', description:'宽体仓库、装卸门与集装箱货场'},
  foodFactory: {zone:'industrial', name:'食品加工', description:'加工厂房、储料筒仓与管道'},
  electronics: {zone:'industrial', footprint:2, cost:960, name:'电子工厂', description:'整洁厂房、蓝色光伏屋顶与设备平台'},
  textile: {zone:'industrial', name:'纺织工厂', architecture:'textile', description:'红砖车间、锯齿采光屋顶与彩色布卷货场'},
  furniture: {zone:'industrial', name:'家具工厂', architecture:'furniture', description:'木色厂房、双坡屋顶、木料堆与成品装卸区'},
  brewery: {zone:'industrial', name:'精酿工坊', architecture:'brewery', description:'暖砖酿造车间、铜色储罐与木桶货场'},
  pharmaceutical: {zone:'industrial', footprint:2, cost:960, name:'制药工厂', architecture:'pharmaceutical', description:'白色生产楼、青蓝玻璃、银色设备与连接管线'},
  machinery: {zone:'industrial', footprint:2, cost:960, name:'机械装配厂', architecture:'machinery', description:'钢结构厂房、桥式吊架、大型卷帘门与零件托盘'},
  shipyard:{zone:'industrial',footprint:2,cost:960,name:'造船厂',architecture:'shipyard',description:'船体装配车间、起重吊架和船台；正常运营后供应居民购买新游艇'},
  carFactory:{zone:'industrial',footprint:2,cost:960,name:'汽车制造厂',architecture:'carFactory',description:'汽车装配车间、采光屋顶与成品车停车场，提供制造业岗位'},
  recycling: {zone:'industrial', name:'再生材料厂', architecture:'recycling', description:'绿色分拣车间、分类料箱、传送带与压缩材料堆'},
};
export const businessKindsFor = zone => Object.keys(BUSINESS_KINDS).filter(id=>BUSINESS_KINDS[id].zone===zone);
export const businessKind = id => Object.hasOwn(BUSINESS_KINDS,id) ? BUSINESS_KINDS[id] : null;
